{{- if hasKey $.Values.nodeManager.internal "cloudProvider" }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.global.clusterConfiguration.cloud.prefix }}
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
  annotations:
    cluster.x-k8s.io/paused: "true"
# A finalizer has been added to prevent cascading removing of all capi resources after deleting the cluster resource.
  finalizers:
    - deckhouse.io/capi-controller-manager
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.global.clusterConfiguration.podSubnetCIDR }}
    services:
      cidrBlocks:
        - {{ .Values.global.clusterConfiguration.serviceSubnetCIDR }}
    serviceDomain: {{ .Values.global.clusterConfiguration.clusterDomain }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
    kind: {{ printf "%sCluster" .Values.global.clusterConfiguration.cloud.provider }}
    namespace: d8-cloud-instance-manager
    name: {{ .Values.global.clusterConfiguration.cloud.prefix }}
---
# empy kubeconfig secret for cluster
apiVersion: v1
data:
  value: Cg==
kind: Secret
metadata:
  name: {{ .Values.global.clusterConfiguration.cloud.prefix }}-kubeconfig
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: cluster.x-k8s.io/secret
{{- end }}
