---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: capi-webhook-tls
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "capi-controller-manager")) | nindent 2 }}
data:
  ca.crt: {{ .Values.nodeManager.internal.webhookCert.ca | b64enc }}
  tls.crt: {{ .Values.nodeManager.internal.webhookCert.crt | b64enc }}
  tls.key: {{ .Values.nodeManager.internal.webhookCert.key | b64enc }}
