---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cert-manager-webhook-tls
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list . (dict "cluster.x-k8s.io/provider" "cluster-api")) | nindent 2 }}
data:
  ca.crt: {{ .Values.certManager.internal.webhookCert.ca | b64enc }}
  tls.crt: {{ .Values.certManager.internal.webhookCert.crt | b64enc }}
  tls.key: {{ .Values.certManager.internal.webhookCert.key | b64enc }}
