---
apiVersion: v1
kind: Service
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "cluster.x-k8s.io/provider" "cluster-api")) | nindent 2 }}
  name: capi-webhook-service
  namespace: d8-capi-system
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: cluster-api
