---
# Source: csi-driver-lvm/templates/common.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: lvm.csi.metal-stack.io
{{ include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | indent 2 }}
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  attachRequired: false
