positive:
  configValues:
  - {}
  values:
  - { internal: {} }
  - https:
      mode: CustomCertificate
      customCertificate:
        secretName: "plainstring"
    internal:
      customCertificateData:
        tls.crt: plainstring
        tls.key: plainstring
      ui:
        ca: CACA
        cert: CERT
        key: KEY
negative:
  configValues:
  - { somethingInConfig: yes }
  values:
  - { somethingInConfig: yes }
