{{- if hasKey .Values.cloudProviderOvirt.internal "connection" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ovirt-credentials
  namespace: d8-cloud-provider-ovirt
  {{- include "helm_lib_module_labels" (list . (dict "app" "cloud-controller-manager")) | nindent 2 }}
type: Opaque
data:
  ovirt_url: {{ .Values.cloudProviderOvirt.internal.connection.authURL | b64enc | quote }}
  ovirt_username: {{ .Values.cloudProviderOvirt.internal.connection.username | b64enc | quote }}
  ovirt_password: {{ .Values.cloudProviderOvirt.internal.connection.password | b64enc | quote }}
  ovirt_insecure: {{ .Values.cloudProviderOvirt.internal.connection.tlsInsecure | b64enc | quote }}
  {{- if hasKey .Values.cloudProviderOvirt.internal.connection "caBundle" }}
  ovirt_ca_bundle: {{ .Values.cloudProviderOvirt.internal.connection.caBundle | b64enc | quote }}
  {{- end }}
{{- end }}
