{{- define "ovirt_cloud_config" }}
  {{- $internal := .Values.cloudProviderOvirt.internal }}
url: {{ $internal.connection.authURL }}
username: {{ $internal.connection.username }}
password: {{ $internal.connection.password }}
  {{- if $internal.connection.caBundle }}
cafile: /etc/config/ca.crt
  {{- end }}
insecure: {{ $internal.connection.tlsInsecure }}
datacenter: Default
cluster: Default
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: capi-ovirt-controller
  namespace: d8-cloud-provider-ovirt
  {{- include "helm_lib_module_labels" (list . (dict "app" "cloud-controller-manager")) | nindent 2 }}
type: Opaque
data:
  OS_CLOUD: {{ include "ovirt_cloud_config" . | b64enc | quote }}
{{- if hasKey .Values.cloudProviderOvirt.internal.connection "caBundle" }}
  ca.crt: {{ .Values.cloudProviderOvirt.internal.connection.caBundle | b64enc | quote }}
{{- end }}
