# permissions for end users to edit clusterimagesources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterimagesource-editor-role
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - clusterimagesources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - clusterimagesources/status
  verbs:
  - get
