# permissions for end users to edit ipaddressreservations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipaddressreservation-editor-role
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - ipaddressreservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - ipaddressreservations/status
  verbs:
  - get
