---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - disks/finalizers
  verbs:
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - disks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - disktypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - disktypes/finalizers
  verbs:
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - disktypes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - ipaddressleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - ipaddressleases/finalizers
  verbs:
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - ipaddressleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - publicimagesources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - publicimagesources/finalizers
  verbs:
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - publicimagesources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - deckhouse.io
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
