---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capo-controller-manager
  namespace: d8-cloud-provider-openstack
  {{- include "helm_lib_module_labels" (list . (dict "app" "capo-controller-manager")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:cloud-provider-openstack:capo-controller-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "capo-controller-manager")) | nindent 2 }}
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - cluster.x-k8s.io
  resources:
    - clusters
    - clusters/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - cluster.x-k8s.io
  resources:
    - machines
    - machines/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - infrastructure.cluster.x-k8s.io
  resources:
    - openstackclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - infrastructure.cluster.x-k8s.io
  resources:
    - openstackclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - infrastructure.cluster.x-k8s.io
  resources:
    - openstackmachines
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - infrastructure.cluster.x-k8s.io
  resources:
    - openstackmachines/status
  verbs:
    - get
    - patch
    - update
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" "capo-controller-manager")) | nindent 2 }}
  name: capo-controller-manager:capo-leader-election-role
  namespace: d8-cloud-provider-openstack
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" "capo-controller-manager")) | nindent 2 }}
  name: capo-controller-manager:capo-leader-election-rolebinding
  namespace: d8-cloud-provider-openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capo-controller-manager:capo-leader-election-role
subjects:
  - kind: ServiceAccount
    name: capo-controller-manager
    namespace: d8-cloud-provider-openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:cloud-provider-openstack:capo-controller-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "capo-controller-manager")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:cloud-provider-openstack:capo-controller-manager
subjects:
- kind: ServiceAccount
  name: capo-controller-manager
  namespace: d8-cloud-provider-openstack
