---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: {{ .Values.global.clusterConfiguration.cloud.prefix }}
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
  annotations:
    cluster.x-k8s.io/paused: "true"
spec:
  cloudName: openstack
  controlPlaneEndpoint:
    host: ""
    port: 0
  identityRef:
    kind: Secret
    name: cloud-config
  controlPlaneAvailabilityZones: {{ .Values.cloudProviderOpenstack.internal.zones }}
