---
apiVersion: v1
kind: Service
metadata:
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
  name: capi-openstack-webhook-service
  namespace: d8-cloud-provider-openstack
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    app: capi-openstack-controller
