x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      deschedulers:
        type: array
        default: [ ]
        items:
          additionalProperties: true
      replicas:
        type: integer
        default: 1
        minimum: 0
        maximum: 1
