---
apiVersion: v1
kind: Secret
metadata:
  name: d8-node-manager-cloud-provider
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  # obligatory
  type: {{ b64enc "ovirt" | quote }}

  # ovirt
  ovirt_url: { { .Values.cloudProviderOvirt.internal.connection.authURL | b64enc | quote } }
  ovirt_username: { { .Values.cloudProviderOvirt.internal.connection.username | b64enc | quote } }
  ovirt_password: { { .Values.cloudProviderOvirt.internal.connection.password | b64enc | quote } }
  ovirt_insecure: { { .Values.cloudProviderOvirt.internal.connection.tlsInsecure | toString | b64enc | quote } }
  { { - if hasKey .Values.cloudProviderOvirt.internal.connection "caBundle" } }
  ovirt_ca_bundle: { { .Values.cloudProviderOvirt.internal.connection.caBundle | b64enc | quote } }

  {{- $internal := .Values.cloudProviderOvirt.internal }}
  {{- $ovirtValues := dict "connection" dict }}
  {{- if and (hasKey $internal.connection "authURL") ($internal.connection.authURL) }}
    {{- $_ := set $ovirtValues.connection "authURL" $internal.connection.authURL }}
  {{- else }}
    {{ cat "No key authURL in module internal values" $internal.connection.authURL | fail }}
  {{- end }}
  {{- if and (hasKey $internal.connection "username") ($internal.connection.username)}}
    {{- $_ := set $ovirtValues.connection "username" $internal.connection.username }}
  {{- else }}
    {{ cat "No key username in module internal values" $internal.connection.username | fail }}
  {{- end }}
  {{- if and (hasKey $internal.connection "password") ($internal.connection.password) }}
    {{- $_ := set $ovirtValues.connection "password" $internal.connection.password }}
  {{- else }}
    {{ cat "No key password in module internal values" $internal.connection.password | fail }}
  {{- end }}
  {{- if hasKey $internal.connection "caBundle" }}
    {{- $_ := set $ovirtValues.connection "caBundle" $internal.connection.caBundle }}
  {{- end }}
  {{- if hasKey $internal.connection "tlsInsecure" }}
    {{- $_ := set $ovirtValues.connection "tlsInsecure" $internal.connection.tlsInsecure }}
  {{- end }}
  ovirt: {{ $ovirtValues | toJson | b64enc | quote }}
