apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: {{ .Chart.Name }}-flowschema
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: cluster-low
  rules:
    - resourceRules:
        - apiGroups:
            - '*'
          clusterScope: true
          namespaces:
            - '*'
          resources:
            - '*'
          verbs:
            - 'list'
      subjects:
      - serviceAccount:
          name: cert-exporter
          namespace: d8-monitoring
        kind: ServiceAccount
      - serviceAccount:
          name: events-exporter
          namespace: d8-monitoring
        kind: ServiceAccount
      - serviceAccount:
          name: extended-monitoring-exporter
          namespace: d8-monitoring
        kind: ServiceAccount
      - serviceAccount:
          name: image-availability-exporter
          namespace: d8-monitoring
        kind: ServiceAccount
