apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackdiscoverydatasets.deckhouse.io
  labels:
    heritage: deckhouse
    module: cloud-provider-openstack
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: openstackdiscoverydatasets
    singular: openstackdiscoverydataset
    kind: OpenStackDiscoveryData
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
      schema: &schema
        openAPIV3Schema:
          type: object
          description: |
            Contains information about data discovered from the cloud.
          required:
            - mainNetwork
            - images
            - defaultImageName
            - zones
          properties:
            mainNetwork:
              type: string
              minLength: 1
              description: |
                The path to the network that will serve as the primary network (the default gateway) for connecting to the virtual machine.
            images:
              type: array
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    minLength: 1
                    description: Virtual machine image name.
              minItems: 1
              description: List of virtual machine images.
            defaultImageName:
              type: string
              minLength: 1
              description: Virtual machine image name used by default.
            zones:
              type: array
              items:
                type: string
                minLength: 1
              minItems: 1
              description: Availability zones.
