positive:
  configValues:
    - {}
  values:
    - internal:
        connection:
          authURL: http://my.cloud.lalla/1/
          username: myuser
          password: myPaSs
          caBundle: mycacert
    - internal:
        connection:
          authURL: http://my.cloud.lalla/2/
          username: myuser
          password: myPaSs
          tlsInsecure: true
negative:
  configValues:
    - { somethingInConfig: yes }
  values:
    - { somethingInConfig: yes }
