x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      connection:
        type: object
        x-examples:
          - { "authURL": "http://cloud.ovirt/ovirt-engine", "caBundle": "mycacert",  "username": "myuser", "password": "mypass", "tlsInsecure": false }
        x-required-for-helm:
          - authURL
          - username
          - password
        properties:
          authURL:
            type: string
          caBundle:
            type: string
          username:
            type: string
          password:
            type: string
          tlsInsecure:
            type: boolean
