x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      statement:
        type: string
        default: "default_unchanged_value_you_should_not_see"
      count:
        type: integer
        default: 0
