---
{{- include "helm_lib_flow_schema_apiversion" (list .) }}
kind: PriorityLevelConfiguration
metadata:
  name: cluster-critical
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse")) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 50
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  name: cluster-high
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse")) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 20
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  name: cluster-medium
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse")) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 10
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  name: cluster-low
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse")) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 5
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
