# PriorityLevelConfiguration queuing is described here
# https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#queuing and here
# https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#prioritylevelconfiguration.
# Additional info about queuing algorithm can be found here -
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness.
---
{{- include "helm_lib_flow_schema_apiversion" (list .) }}
kind: PriorityLevelConfiguration
metadata:
  name: cluster-critical
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 50
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
{{- include "helm_lib_flow_schema_apiversion" (list .) }}
kind: PriorityLevelConfiguration
metadata:
  name: cluster-high
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 20
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
{{- include "helm_lib_flow_schema_apiversion" (list .) }}
kind: PriorityLevelConfiguration
metadata:
  name: cluster-medium
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 10
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
---
{{- include "helm_lib_flow_schema_apiversion" (list .) }}
kind: PriorityLevelConfiguration
metadata:
  name: cluster-low
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 5
    limitResponse:
      queuing:
        handSize: 4
        queueLengthLimit: 50
        queues: 16
      type: Queue
