---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linstor-scheduler-admission
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-scheduler-admission")) | nindent 2 }}
webhooks:
- name: scheduler-admission.linstor.deckhouse.io
  namespaceSelector:
    matchExpressions:
    - key: linstor-scheduler-admission.deckhouse.io/disabled
      operator: DoesNotExist
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - d8-system
      - kube-system
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "*"
  clientConfig:
    service:
      namespace: "d8-linstor"
      name: "linstor-scheduler-admission"
      path: "/mutate"
      port: 4443
    caBundle: {{ .Values.linstor.internal.webhookCert.ca | b64enc }}
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 10
