apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticinstancecredentials.deckhouse.io
  labels:
    heritage: deckhouse
    module: node-manager
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: staticinstancecredentials
    singular: staticinstancecredential
    kind: StaticInstanceCredential
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines credentials for connect to a static instance. Uses in StaticInstance resource.
          properties:
            spec:
              type: object
              required: ["user", "privateSSHKey"]
              description: Specification of the desired behavior of the static instance credentials.
              properties:
                user:
                  type: string
                  description: Username for connect to static instance.
                privateSSHKey:
                  type: string
                  description: SSH private key for connect to static instance.
                sudoPassword:
                  type: string
                  description: Password for getting root permissions.
                sshPort:
                  type: number
                  description: SSH connection port.
                sshExtraArgs:
                  type: string
                  description: Extra argument for passing to ssh client.
